CAMERA_INDEX = 0

BACKEND_API = "http://localhost:8080/api"

EAR_THRESHOLD = 0.25

DROWSY_CONSECUTIVE_FRAMES = 20

SLEEPING_CONSECUTIVE_FRAMES = 60

DROWSINESS_SECONDS = 2

YAWN_THRESHOLD = 0.60

YAWN_CONSECUTIVE_FRAMES = 15

ALARM_SOUND_PATH = "assets/alarm.wav"

BACKEND_API_URL = "http://localhost:8080/api"

JWT_TOKEN = "eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJkZXZpc3Jpc2VudGhpbGt1bWFyMjZAZ21haWwuY29tIiwiaWF0IjoxNzgzNjY1NjIwLCJleHAiOjE3ODM3NTIwMjB9.-dl8KRV-f3QsrJgu0JzKrE84ljtyIO4Ox0RNVCT01yuulR19gtNx6veZXZzMDxO6"
